sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "t4+zwRz1SwsdKUx/VTBdXPY5X4IvFLLtyym7ChH20H+EUnuhXMv8uvH9GB5tQO1AWlVMFU+FXmGeVFTCyxWIupJ350+c9ADxW3ur/G68++6R4cvRPPqZbBnoGQoVHn78Q1WTPHxTakhSv91/NrFr9N3CraPVeln9Gi4dqz32CmBPc6MaKVuqJCWDha6C1e9xp0q+y7qo5mK68VaAOzqk/SRR5cG6Z2JWj9Rw+mcnc2gXGM4eU3WDwuK+d5PPIVfIeiibWkaXMEbr6cvVxRNu9jL+nJuJ2dnujfrjpqCuffD7i5l4bck+IeQDP6gNk1ashTVrBnz+o3pEcsHLhiTUgK7Bq9PVPV3knDytP1uki4YOqPmcj1G3Rktk0nL5mrFihB1ln4G8q3mf3IJttkbDR1hjto1NcHAzJOJgBQ8UGDvNb4vfSt5udjIdWjZaWxbX85sFio2nh/Q9Xrsc5PpIxfMIE/0P3FyuLYtKP1/B0SEbCFQm1GR1jWR7QkTZxoAB0/fYIw6F0AzH/gyDiZhsWk+Q3V8pCdrybFZk8PY1qrZirU3tqMni5uMMfkTBNstkvuPQq3c9g8mDru+DT6jRNzNtDyna4+KIyva7gdydUfZ6QFG0lUMsg5tfKhwJt/g7JC1T7muaw2PrL2l78Er+oEqkv1SK7mg/4oDfJq/7F1s="
  - secure: "PyqAMRlMpWSQCrOgAzhFQ9T1LbeYdsT/l+LDN5lvs532AjBbzKUGJpMdDBwozGGg/4PiPe/fqQwqKMLNtRLICkFGf35W3QBu1KIBLKfGjVLZogsTeTaaMEuZb+bq9rZGxUdlcFMjahyP/rZExviVCuJFMDPQCEBIMFKrzoZdV4eogj8nPv4DBEf0TX7gpDxqwKu0V4MhPLYBbVm4iag4DUPnO01g96pWd1lSjsfRRvoLvhKeGnO1InSIWHNx6HDdFn/dmp58wJEwu/dIiQ41Ra9iYHNi6ti4ARkJKK5U7DodZZXrFlW4htplETElTcGJUb3LEz2asFJXLe7FWzoxwU614Hgwxj3UJFFfjhS6ATbPiGWhP39lXkHHJnROn0/c/9C5x5lSs/aHqqOS/PuDZ9rkCjQ4nRY7sjlNGUh8b6t/XU6ygqcOums5jKTsr9F9NMB755tVXGh9h/RxXJMCGN2u2I+w1+glZkVWMms/Tw7vunK6uwdG13vrBDLNszQQzgOMtpUwAa0t1QQyYJ2yze2mNMUZ4lEbz+19n3Vf8EuRlyobM8/0cKZHUrb3xUBDuCiOBX4q1epM/Kkan5Ttkz56OblMkduOedGbR8AVfd/8y5iMvlgGcBM+UXPq9HlBtbmUl+OaM1ETkFuhUzBx4YHfFlGrlvBD5B41SPqB8Hg="
  - secure: "uv3jLwUc00/3PvEqAvgwBA1/AuSuP255qHl6uTD2zrKju/U+XyNIJMfZ1lSiopT/9wv8LmeeNOB2OKmyA+715rZCalv6SGPnTrLPDZdKIm0rzWOmSBMIauFVDNJwd7hGHMJHxozNQ+D4NHVOJmytjJR3K3gftrJT4KAaxDYlBC4C9BH/7tE7/k1STAmHxkRLLkjNkE5FUgahUVaXM0UAjxH+4AQHGAZvyiLdcxtS0rn5Q29JBmWkoRBFBbuApHkuTSEGople+5Em2JqvbHxRGH/l4vwSD7QOVzAWA6gigEBRgCLbtEAQ3oDy3R9t7YOHt2DErhFbTTuePUq6xWo2NB8rzbjNW6QF8x8ukguIu/AfeI+0fILUzYVpnuj908LIbvgSV39ec7uaFjFS7Qe1Pd+6XRsYnCLfxHINau3v3LtCt5iFynBNCSNBLpeZCBhCN3/LJ5wCnKYb/+xTNV6CZyEAuWZWxxRk/XFkmpTzikoqWRupsBwvgOd3U0AC7qRQxfjIPREnqIypKSPRukJ1OKqQC60vtxj5IdKlOFdyewaITlVYwlTsIW18M39ucAu85rhkQlinmKNL+tvqjsQMrv/S8LkCvKJCZHRqbx931Ie4XL2iHMB/3RRWlPizt7zx7o3nHS29F5DQv3of6QCvRHojU/VkTRx6lOr/Y1WwpnA="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
